env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./config.js
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-native
  - "@typescript-eslint"
rules: {}
